blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/outline/outline/discussions/new
    about: Request a feature to be added to the project
  - name: Self Hosting Questions
    url: https://github.com/outline/outline/discussions/new
    about: Ask questions and discuss running Outline with community members
  - name: Hosted Support
    url: mailto:hello@getoutline.com
    about: Get support with your team account on getoutline.com
