services:
  outline:
    image: netis/house-outline:1.0.1
    env_file: ./docker.env
    ports:
      - "443:443"
      - "80:80" # 可选：做 http->https 重定向或排障
    environment:
      - PORT=443
      - FORCE_HTTPS=true
    volumes:
      # 把你的证书挂到容器内应用根目录（示例 /opt/outline）
      - ./certs/public.pem:/opt/outline/public.pem:ro
      - ./certs/private.pem:/opt/outline/private.pem:ro
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7
    expose: [ "6379" ]

  postgres:
    image: postgres:16
    env_file: ./docker.env
    expose: [ "5432" ]
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  storage-data:
  database-data:


